app_shop/urls.py
from django.conf.urls import url
from django.urls import include

from . import views


authentication = [
    url(r'^login$', views.authentication, name='authentication'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^registration$', views.registration, name='registration'),
    url(r'^user_account$', views.user_account, name='user_account'),
]

shopping = [
    url(r'^product/(?P<slug>\S+)$', views.ProductDetailView.as_view(), name='product_detail'),
    url(r'^category/(?P<category_id>\S+)$', views.CategoryListView.as_view(), name='section_products'),
    url(r'^change_user_shop/(?P<shop_id>\w+)$', views.change_user_shop, name='change_user_shop'),
    url(r'^search$', views.search, name='search'),
]

cart = [
    url(r'^$', views.cart, name='cart'),
    url(r'^add_product/(?P<product_id>\w+)$', views.add_product_to_cart, name='add_product'),
    url(r'^remove_from_cart/(?P<product_id>\w+)$', views.remove_product_from_cart, name='remove_product'),
    url(r'^remove_one_from_cart/(?P<product_id>\w+)$', views.remove_one_from_cart, name='remove_one_copy'),
    url(r'^empty_trash/', views.empty_trash, name='empty_trash'),
    url(r'^send_order$', views.send_order, name='send_order'),
]

app_name = 'app_shop'
urlpatterns = [
    url(r'^subscription$', views.subscription, name='subscription'),
    url(r'^auth/', include(authentication)),
    url(r'^cart/', include(cart)),
    url(r'^shopping/', include(shopping)),
    url(r'^(?P<page>\w+)?$', views.main_sub_pages, name='main_sub_pages'),
]

shop_allhere/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from app_shop import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('allhere.ru/', include('app_shop.urls')),
    path('allhere_in_russia/', include('allhere_in_russia.urls')),
    path('', RedirectView.as_view(url='/allhere.ru/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = views.handler403
handler404 = views.handler404
handler500 = views.handler500

app_shop/models/information.py
from django.db import models


class SubscriptionEmails(models.Model):
    email = models.EmailField(max_length=40, help_text="Enter email for mailing", unique=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Mailing address'
        verbose_name_plural = 'Postal addresses'


class VisitStatistics(models.Model):
    url_address = models.CharField(max_length=200)
    user_id = models.PositiveSmallIntegerField(null=True, blank=True)
    actions = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.id

    class Meta:
        verbose_name = 'Page visit'
        verbose_name_plural = 'Page visits'

app_shop/models/information_models.py
from django.db import models


class SubscriptionEmails(models.Model):
    email = models.EmailField(max_length=40, help_text="Enter email for mailing", unique=True)

    def __str__(self):
        return self.email

    class Meta:
        app_label = 'app_shop'
        verbose_name = 'Mailing address'
        verbose_name_plural = 'Postal addresses'


class VisitStatistics(models.Model):
    url_address = models.CharField(max_length=200)
    user_id = models.PositiveSmallIntegerField(null=True, blank=True)
    actions = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.id

    class Meta:
        app_label = 'app_shop'
        verbose_name = 'Page visit'
        verbose_name_plural = 'Page visits'

app_shop/views/handlers_errors.py
from django.shortcuts import render


def handler403(request, *args, **kwargs):
    return render(request, 'handlers/403.html', status=403)


def handler404(request, *args, **kwargs):
    return render(request, 'handlers/404.html', status=404)


def handler500(request, *args, **kwargs):
    return render(request, 'handlers/500.html', status=500)

app_shop/views/site_function.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render

from app_shop.forms import SearchForm, SubscriptionForm
from app_shop.models import Product, ProductClassification, SubscriptionEmails


def search(request):
    form = SearchForm(request.GET)
    if not form.is_valid():
        return HttpResponseRedirect(request.path)

    key = form.cleaned_data.get("search_key")
    object_list = Product.objects.filter(Q(name__icontains=key) | Q(description__icontains=key))
    category_ids = object_list.values_list('classification_id', flat=True)
    category_list = ProductClassification.objects.filter(id__in=category_ids)
    return render(
        request,
        'search_results.html',
        context={
            'object_list': object_list,
            'key': key,
            'category_list': category_list
            }
    )


def subscription(request):
    form = SubscriptionForm(request.POST)
    if not form.is_valid():
        return redirect(request.GET['next'])

    SubscriptionEmails.objects.get_or_create(**form.cleaned_data)
    return redirect(request.GET['next'])

app_shop/views/site_rendering.py
from django.db.models import Count, Max, Min, Subquery, OuterRef
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic

from app_shop.forms import PriceForm, FiltersForm
from app_shop.models import (
    ClassificationFilters, FiltersForClassifications, Promotions,
    Product, ProductClassification, ProductListForOrder, ProductQuantity
)
from shop_allhere.utils import get_promotions_for_category


def main_sub_pages(request, **kwargs):
    context_content = {}
    if not kwargs:
        template_name = 'index.html'
        context_content['promotions_for_carousel'] = Promotions.objects.filter(for_carousel=True)
        context_content['highest_categories'] = ProductClassification.objects.filter(highest_category=True)
    else:
        template_name = 'main_subpages/%s.html' % kwargs['page']

    context_content['promotions_ordinary'] = list(Promotions.objects.filter(
        for_category=None, for_carousel=False).order_by('?')[:5])
    return render(request, template_name, context={**context_content})


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'product_detail.html'

    def get_context_data(self, **kwargs):
        self.object.count = (ProductQuantity.objects.get(
            shop_id=self.request.session['shop'], product_id=self.object.id)).number

        list_orders_id = ProductListForOrder.objects.filter(
            product_id=self.object.id).values_list('orderlist_id', flat=True)
        most_often_buy = ProductListForOrder.objects.filter(
            orderlist_id__in=list_orders_id).exclude(product_id=self.object.id).values('product_id').annotate(
            count=Count("id")).order_by('-count')[:5]
        most_often_buy = most_often_buy.values_list('product_id', flat=True)
        also_buy_products = Product.objects.filter(id__in=most_often_buy)

        similiar_products = Product.objects.filter(
            classification=self.object.classification).exclude(
            id=self.object.id).order_by('?')[:5]

        promotions_for_page = get_promotions_for_category([self.object.classification_id])

        context = {
            'also_buy_products': also_buy_products,
            'similiar_products': similiar_products,
            'promotions_for_page': promotions_for_page,
            **kwargs
        }
        return super().get_context_data(**context)


class CategoryListView(generic.ListView):
    model = ProductClassification
    template_name = 'section_products.html'

    def get_queryset(self):
        query_dictionary = {}
        order = self.request.GET.get('sorted', None)
        if order not in ['price', '-price']:
            order = 'name'

        if self.kwargs:
            filters_form = FiltersForm(self.request.GET)
            if not filters_form.is_valid():
                return HttpResponseRedirect(self.request.path)

            for filter_key, filter_value in filters_form.data.items():
                if filter_key != 'price' and filter_value:
                    filter_obj = FiltersForClassifications.objects.filter(name=filter_key).first()
                    if filter_obj:
                        if filter_obj.type == "INT":
                            query_dictionary['specifications__' + filter_key + '__lte'] = float(filter_value)
                        elif filter_obj.type == "CSM":
                            query_dictionary['specifications__' + filter_key + '__in'] = self.request.GET.getlist(filter_key)
                elif filter_value:
                    query_dictionary['the_final_price__lte'] = float(filter_value)

        def recursive_get_childs(item):
            yield item.id
            for child in item.get_child():
                yield from recursive_get_childs(child)

        self.kwargs['category'] = ProductClassification.objects.get(id=self.kwargs['category_id'])
        self.kwargs['category_ids'] = list(recursive_get_childs(self.kwargs['category']))
        query_dictionary['classification_id__in'] = self.kwargs['category_ids']

        products_quantity = ProductQuantity.objects.filter(
            shop_id=self.request.session['shop'],
            product_id=OuterRef('id')
        )
        self.queryset = Product.objects.filter(**query_dictionary).order_by('classification', order).annotate(
            count=Subquery(products_quantity.values_list('number', flat=True)[:1])
        )
        return self.queryset

    def get_context_data(self, **kwargs):
        form_dictionary = {}

        self.kwargs['category_ids'] = self.queryset.values_list('classification_id', flat=True)

        promotions_for_page = get_promotions_for_category(self.kwargs['category_ids'])
        product_listing_ads = Promotions.objects.select_related('advertising').filter(
            advertising__obligatory=True).order_by("?")[:5]

        price_values = self.queryset.aggregate(
            min_price=Min('the_final_price'), max_price=Max('the_final_price'))
        price_form = PriceForm(min_value=price_values['min_price'])
        form_dictionary['price_form'] = price_form

        filter_list = ClassificationFilters.objects.filter(
            classification_id=self.kwargs['category_id']).values('filter__name', 'filter__type', 'filter__priority')

        form_filters = []
        for filter_object in filter_list:
            if filter_object['filter__type'] != 'TXT':
                value = self.queryset.values_list('specifications__' + filter_object['filter__name'], flat=True)
                if filter_object['filter__type'] == 'INT':
                    filter_object['filter__values'] = [min(value), max(value)]
                elif filter_object['filter__type'] == 'CSM':
                    filter_object['filter__values'] = value
            form_filters.append(filter_object)

        filters_form = FiltersForm(filters=form_filters)
        form_dictionary['filters_form'] = filters_form

        context = {
            'category': self.kwargs['category'],
            'promotions_for_page': promotions_for_page,
            'product_listing_ads': product_listing_ads,
            'price_values': price_values,
            **form_dictionary,
            **kwargs,
        }
        return super().get_context_data(**context)

app_shop/views/trading.py
from django.db.models import OuterRef, Subquery
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render

from app_shop.forms import OrderForm
from app_shop.models import OrderList, Product, ProductListForOrder, ProductQuantity
from shop_allhere import constants


def change_user_shop(request, shop_id):
    request.session['shop'] = int(shop_id)
    return HttpResponseRedirect(request.GET['next'])


def cart(request):
    if not request.session.get('cart', False):
        return render(request, 'cart.html', context={
                'total_cost': 0,
                'shortage': constants.MINIMUM_ORDER_AMOUNT}
        )

    products_quantity = ProductQuantity.objects.filter(
        shop_id=request.session['shop'],
        product_id=OuterRef('id')
    )

    products_ids = request.session["cart"]
    products_in_cart = Product.objects.filter(id__in={**products_ids}.keys()).annotate(
        count=Subquery(products_quantity.values_list('number', flat=True)[:1]))

    cost_list = {
        str(item.id): round(float(item.get_current_prices()) * products_ids[str(item.id)], 2)
        for item in products_in_cart
    }

    total_cost = round(sum(cost_list.values()), 2)
    shortage = round(constants.MINIMUM_ORDER_AMOUNT - sum(cost_list.values()), 2)

    return render(
        request,
        'cart.html',
        context={
            'order_form': OrderForm(),
            'products_in_cart': products_in_cart,
            'cost_list': cost_list,
            'total_cost': total_cost,
            'shortage': shortage,
        }
    )


def add_product_to_cart(request, product_id):
    count = request.session['cart'].get(product_id, 0)
    request.session['cart'][int(product_id)] = count + 1
    return HttpResponseRedirect(request.GET['next'])


def remove_product_from_cart(request, product_id):
    if product_id in request.session['cart']:
        request.session["cart"].pop(product_id)
    return HttpResponseRedirect(request.GET['next'])


def remove_one_from_cart(request, product_id):
    if product_id in request.session['cart']:
        count = request.session['cart'].get(product_id, 0)

        if count <= 1:
            request.session["cart"].pop(product_id)
            return HttpResponseRedirect(request.GET['next'])

        request.session['cart'][product_id] -= 1
    return HttpResponseRedirect(request.GET['next'])


def empty_trash(request):
    request.session['cart'] = {}
    return redirect('/allhere.ru/cart/')


def send_order(request):
    form = OrderForm(request.POST)
    if not form.is_valid():
        return HttpResponseRedirect(request.path)

    products_id = request.session["cart"]
    products_in_cart = Product.objects.filter(id__in={**products_id}.keys())

    cost_list = {
        str(item.id): float(item.get_current_prices()) * products_id[str(item.id)]
        for item in products_in_cart
    }
    total_cost = round(sum(cost_list.values()), 2)

    form_data = {
        key: value
        for key, value in form.cleaned_data.items() if value
    }

    if request.user.is_authenticated:
        form_data['customer_id'] = request.user.id

    obj = OrderList.objects.create(
        cost=total_cost,
        **form_data
    )

    for name, count in request.session["cart"].items():
        ProductListForOrder.objects.create(
            orderlist_id=obj.id,
            product_id=name,
            store=request.session['shop'],
            count=count
        )

    request.session["cart"] = {}
    return redirect('/allhere.ru/cart/')

app_shop/templates/authentication.html
{% extends "base_generic.html" %}


{% load static %}
{% load crispy_forms_tags %}

{% block content %}
  {% if form.errors %}
    <div class="alert alert-danger text-center fade show" role="alert">
      <strong>Действие закончилось неудачей!</strong> Проверьте правильность введённых данных и повторите попытку:
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <div class="w-50 m-auto">
        {% for error in form.errors.items %}
          <strong>{{ error.1|escape }}</strong>
        {% endfor %}
      </div>
    </div>
  {% endif %}
  <div class="authentication col-11 col-lg-7 col-xl-5">
    <nav class="authentication__nav-tabs nav nav-tabs" id="nav-tab" role="tablist">
      <a class="authentication__tabs-item nav-link {% if not authorization %}active{% endif %}"
         id="nav-registration-tab" data-toggle="tab" href="#nav-registration" role="tab"
         aria-controls="nav-home" aria-selected="true">РЕГИСТРАЦИЯ</a>
      <a class="authentication__tabs-item nav-link {% if authorization %}active{% endif %}"
         id="nav-profile-tab" data-toggle="tab" href="#nav-authorization" role="tab"
         aria-controls="nav-profile" aria-selected="false">АВТОРИЗАЦИЯ</a>
    </nav>
    <div class="authentication__content-block tab-content" id="nav-tabContent">
      <div class="authentication__tabpanel tab-pane fade {% if not authorization %}show active{% endif %}"
           id="nav-registration" role="tabpanel" aria-labelledby="nav-registration-tab">
        <form class="authentication__form" action="{% url 'app_shop:registration' %}" method="post">
          <div class="authentication__form-content">
            {% csrf_token %}
            {{ registration_form|crispy }}
            <button type="submit" class="authentication__button">Зарегистрироваться</button>
          </div>
        </form>
      </div>
      <div class="authentication__content-block tab-pane fade {% if authorization %}show active{% endif %}"
           id="nav-authorization" role="tabpanel" aria-labelledby="nav-authorization-tab">
        <form class="authentication__form" action="{% url 'app_shop:authentication' %}" method="post">
          <div class="authentication__form-content">
            {% csrf_token %}
            {{ authorization_form|crispy }}
            <button type="submit" class="authentication__button">Авторизироваться</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

{% block promo %}
{% endblock %}

{% block text-info %}
{% endblock %}

{% block links-subscription %}
{% endblock %}

app_shop/templates/cart.html
{% extends "base_generic.html" %}


{% load static %}
{% load crispy_forms_tags %}

{% block title %}<title>AllHere интернет-магазин | Корзина покупателя</title>{% endblock %}

{% block content %}
  <div class="cart-block">
    <div class="cart-title col-12">
      <h2 class="cart-title__title">Сейчас в корзине {% if not products_in_cart %}ничего нет{% endif %}</h2>
    </div>
    <div class="cart-block__product col-12 col-lg-9 col-xl-8">
      {% if products_in_cart %}
        <ol class="cart-block__list-product">
          {% for object in products_in_cart %}
            <li class="cart-block__item cart-item">
              <article class="cart-item__block">
                <div class="cart-item__image-block">
                  <img class="cart-item__image" src="{{ object.images.url }}" alt="{{ object.name }}">
                </div>
                <div class="cart-item__name">
                  <a href="{% url 'app_shop:product_detail' object.slug %}">{{ object.name }}</a>
                </div>
                <div class="cart-item__numbers">
                  <div class="btn-group" role="group" aria-label="Basic example">
                    {% for key, value in request.session.cart.items %}
                      {% if key == object.id|slugify %}
                        {% if object.count > value %}
                          <a class="cart-item__numbers-button btn"
                             href="{% url 'app_shop:add_product' object.id %}?next={{ request.path }}">+</a>
                        {% endif %}
                        <p class="cart-item__numbers-value">{{ value }}</p>
                        <a class="cart-item__numbers-button btn"
                           href="{% url 'app_shop:remove_one_copy' object.id %}?next={{ request.path }}">-</a>
                      {% endif %}
                    {% endfor %}
                  </div>
                  <p>{{ object.get_current_prices }} &#8381; / шт</p>
                  <p>Всего на складе {{ object.count }} шт</p>
                </div>
                <div class="cart-item__cost">
                  {% for key, value in cost_list.items %}
                    {% if key == object.id|slugify %}
                      <p>{{ value }} &#8381;</p>
                    {% endif %}
                  {% endfor %}
                </div>
                <div class="cart-item__delete">
                  <a class="stretched-link"
                     href="{% url 'app_shop:remove_product' object.id %}?next={{ request.path }}"></a>
                  <div class="cart-item__delete-image"></div>
                </div>
              </article>
            </li>
          {% endfor %}
        </ol>
      {% endif %}
    </div>
    <div class="cart-block__count col-12 col-lg-3 col-xl-4">
      <div class="cart-block__count-header">
        <h2>Итого</h2>
        {% if shortage > 0 %}
          <p class="cart-block__count-warning">До минимальной суммы заказа осталось {{ shortage }} &#8381;</p>
        {% endif %}
      </div>
      <hr>
      <div class="cart-block__count-body">
        <table class="cart-block__count-table">
          <tr>
            <td>Товары({{ products_in_cart|length }})</td>
            <td>{{ total_cost }} &#8381;</td>
          </tr>
          <tr>
            <td>Стоимость самовывоза</td>
            <td>Бесплатно</td>
          </tr>
          <tr>
            <td><b>Всего к оплате</b></td>
            <td><b>{{ total_cost }} &#8381;</b></td>
          </tr>
        </table>
        {% if shortage <= 0 %}
          <div class="cart-block__button-block">
            <button type="button" class="cart-item__numbers-button btn btn-danger" data-toggle="modal"
                    data-target="#OrderingModal">Перейти к оформлению
            </button>
          </div>
        {% endif %}
      </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="OrderingModal" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog"
         aria-labelledby="OrderingModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h2 class="modal-title" id="OrderingModalLabel">Куда доставить?</h2>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="{% url 'app_shop:send_order' %}" method="post">
              {% csrf_token %}
              {% if user.is_authenticated and products_in_cart %}
                {{ order_form.address|as_crispy_field }}
              {% else %}
                {{ order_form|crispy }}
              {% endif %}
              <button type="button" class="btn btn-lg btn-secondary" data-dismiss="modal">Отмена</button>
              <button type="submit" class="btn btn-lg btn-primary">Отправить заявку</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal end -->
    {% if products_in_cart %}
      <a class="cart-block__trash-button btn btn-outline-danger"
         href="{% url 'app_shop:empty_trash' %}?next={{ request.path }}"
         role="button">Очистить корзину</a>
    {% endif %}
  </div>
{% endblock %}

{% block promo %}
{% endblock %}

{% block text-info %}
{% endblock %}

app_shop/templates/product_detail.html
{% extends "base_generic.html" %}


{% load static %}

{% block title %}<title>AllHere интернет-магазин | {{ object.name }}</title>{% endblock %}

{% block content %}
  <div class="product-block">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb bg-white my-0">
        <li class="breadcrumb-item"><a href="{% url 'app_shop:main_sub_pages' %}">Главная страница</a></li>
        {% for category in object.classification.get_parent %}
          {% if not forloop.last %}
            <li class="breadcrumb-item" aria-current="page"><a
                href="{% url 'app_shop:section_products' category.id %}">{{ category.name }}</a></li>
          {% else %}
            <li class="breadcrumb-item active" aria-current="page">{{ category.name }}</li>
          {% endif %}
        {% endfor %}
      </ol>
    </nav>
    <hr>
    <div class="product-block__info-block col-12">
      <div class="product-block__top-block">
        <div class="top-block__image-container">
          <img class="top-block__image" src="{{ object.images.url }}" alt="{{ object.name }}">
        </div>
        <div class="top-block__title-container">
          <h2 class="top-block__title">{{ object.name }}</h2>
        </div>
        <div class="top-block__price-container">
          {% if object.get_current_discount %}
            <div class="top-block__discount">
              <p class="top-block__discount-text">На товар действует скидка!</p>
              <p class="top-block__discount-text">{{ object.get_current_discount }}</p>
            </div>
          {% endif %}
          <div class="top-block__price">
            <p class="top-block__price-text">{{ object.get_current_prices }} &#8381; / шт</p>
            {% if object.count %}
              <p class="top-block__price-text">В наличии: {{ object.count }}</p>
            {% else %}
              <p class="top-block__price-text">Нет в наличии</p>
            {% endif %}
            {% if object.id|slugify in request.session.cart.keys %}
              <a class="top-block__buy-button btn btn-danger"
                 href="{% url 'app_shop:remove_product' object.id %}?next={{ request.path }}">Удалить из корзины</a>
            {% elif object.count > 0 %}
              <a class="top-block__buy-button btn btn-success"
                 href="{% url 'app_shop:add_product' object.id %}?next={{ request.path }}">В корзину</a>
            {% endif %}
          </div>
        </div>
      </div>
      <div class="product-info__bottom-block">
        <div class="bottom-block__description-container">
          <h2 class="bottom-block__title">О товаре</h2>
          <div class="bottom-block__description">{{ object.description|safe }}</div>
        </div>
        <div class="bottom-block__characteristic-container">
          <h2 class="bottom-block__title">Характеристики</h2>
          {% if object.specifications %}
            <table class="bottom-block__table">
            {% for key, value in object.specifications.items %}
              <tr class="bottom-block__table-row">
                <td class="bottom-block__cell">{{ key }}</td>
                <td class="bottom-block__cell">{{ value }}</td>
              </tr>
            {% endfor %}
          {% endif %}
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block promo %}
  <div class="recomendations-block d-none d-sm-block col-12">
    {% if similiar_products %}
      <h2 class="recomendations-block__title">&laquo; Похожие товары &raquo;</h2>
      <div class="recomendations-container">
        {% for product in similiar_products %}
          <div class="recomendations-block__card card">
            <img src="{{ product.images.url }}" class="card-img-top" alt="{{ product.name }}">
            <a class="stretched-link" href="{% url 'app_shop:product_detail' product.slug %}"></a>
            <div class="card-body d-none d-md-block">
              <p class="card-text">{{ product.name }}</p>
            </div>
          </div>
        {% endfor %}
      </div>
    {% endif %}
    {% if also_buy_products %}
      <h2 class="recomendations-block__title">&laquo; С этим товаром покупают &raquo;</h2>
      <div class="recomendations-container">
        {% for product in also_buy_products %}
          <div class="recomendations-block__card card">
            <img src="{{ product.images.url }}" class="card-img-top" alt="{{ product.name }}">
            <a class="stretched-link" href="{% url 'app_shop:product_detail' product.slug %}"></a>
            <div class="card-body d-none d-md-block">
              <p class="card-text">{{ product.name }}</p>
            </div>
          </div>
        {% endfor %}
      </div>
    {% endif %}
    {% if promotions_for_page %}
      <h2 class="recomendations-block__title d-none d-md-block">&laquo; Акции &raquo;</h2>
      <div class="recomendations-promotions d-none d-md-flex">
        {% for promo in promotions_for_page %}
          <div class="promotions-block">
            <img class="promotions-block__image" src="{{ promo.images.url }}" alt="{{ promo.name }}">
          </div>
        {% endfor %}
      </div>
    {% endif %}
  </div>
{% endblock %}

{% block text-info %}
{% endblock %}

app_shop/templates/search_results.html
{% extends "base_generic.html" %}


{% load static %}

{% block title %}<title>AllHere интернет-магазин | Поиск по значению "{{ key }}"</title>{% endblock %}

{% block content %}
  <div class="category-block col-11">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb bg-white my-0">
        <li class="breadcrumb-item"><a href="{% url 'app_shop:main_sub_pages' %}">Главная страница</a></li>
        <li class="breadcrumb-item active" aria-current="page">Поиск по значению "{{ key }}"</li>
      </ol>
    </nav>
    <hr>
    <div class="category-block__list">
      {% if category_list %}
        {% for category in category_list %}
          <h3 class="category-block__section-title">
            <a href="{% url 'app_shop:section_products' category.id %}">{{ category.name }}</a>
          </h3>
          <div class="category-block__list-section">
            {% if object_list %}
              {% for object in object_list %}
                {% if object.classification_id == category.id %}
                <div class="category-block__list-items list-items card">
                  <div class="list-items__image-block">
                    <img src="{{ object.images.url }}" class="list-items__image card-img-top" alt="{{ object.name }}">
                  </div>
                  <div class="list-items__text-block">
                    <ul class="list-items__group">
                      <li class="list-items__group-item"><a
                          href="{% url 'app_shop:product_detail' object.slug %}">{{ object.name }}</a></li>
                      <li class="list-items__group-item">{{ object.price }} &#8381;</li>
                    </ul>
                  </div>
                </div>
                {% endif %}
              {% endfor %}
            {% else %}
              <div class="text-center w-100">
                <h2>По запросу "{{ key }}" ничего не найдено</h2>
              </div>
            {% endif %}
          </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block promo %}
{% endblock %}

{% block text-info %}
{% endblock %}