allhere_in_russia/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views


app_name = 'allhere_in_russia'
urlpatterns = [
    url(r'^$', RedirectView.as_view(url='allhere_in_russia', permanent=False), name='subpage_index'),
    url(r'^(?P<address>\w+)$', views.SubpageAboutCompanyView.as_view(), name='subpages'),
    url(r'^all_shops/(?P<id>\w+)$', views.ShopDetailView.as_view(), name='shop_detail'),
    url(r'^news/(?P<id>\w+)?$', views.NewsDetailView.as_view(), name='news'),
]

app_shop/urls.py
from django.conf.urls import url
from django.urls import include

from . import views


authentication = [
    url(r'^login$', views.authentication, name='authentication'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^registration$', views.registration, name='registration'),
    url(r'^user_account$', views.user_account, name='user_account'),
]

shopping = [
    url(r'^product/(?P<slug>\S+)$', views.ProductDetailView.as_view(), name='product_detail'),
    url(r'^category/(?P<category_id>\S+)$', views.CategoryListView.as_view(), name='section_products'),
    url(r'^change_user_shop/(?P<shop_id>\w+)$', views.change_user_shop, name='change_user_shop'),
    url(r'^search$', views.search, name='search'),
]

cart = [
    url(r'^$', views.cart, name='cart'),
    url(r'^add_product/(?P<product_id>\w+)$', views.add_product_to_cart, name='add_product'),
    url(r'^remove_from_cart/(?P<product_id>\w+)$', views.remove_product_from_cart, name='remove_product'),
    url(r'^remove_one_from_cart/(?P<product_id>\w+)$', views.remove_one_from_cart, name='remove_one_copy'),
    url(r'^empty_trash/', views.empty_trash, name='empty_trash'),
    url(r'^send_order$', views.send_order, name='send_order'),
]

app_name = 'app_shop'
urlpatterns = [
    url(r'^subscription$', views.subscription, name='subscription'),
    url(r'^auth/', include(authentication)),
    url(r'^cart/', include(cart)),
    url(r'^shopping/', include(shopping)),
    url(r'^(?P<page>\w+)?$', views.main_sub_pages, name='main_sub_pages'),
]

shop_allhere/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from app_shop import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('allhere.ru/', include('app_shop.urls')),
    path('allhere_in_russia/', include('allhere_in_russia.urls')),
    path('', RedirectView.as_view(url='/allhere.ru/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = views.handler403
handler404 = views.handler404
handler500 = views.handler500

allhere_in_russia/models.py
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField
from yandex_geocoder import Client

from shop_allhere import constants, settings
from shop_allhere.utils import transliterate


SUBPAGESARTICLE_ADDRESS = "Enter a url address for article, otherwise the address will be set automatically"
SUBPAGESARTICLE_UNIQ_TEMPLATE = "check if the page will use a unique HTML template"
SHOPS_CITY = "Check the city where the store is located"
SHOPS_ADDRESS = "Enter address of shop in the format City, street, house number"
SHOPS_LATITUDE = "indicates the latitude of the location on the world map"
SHOPS_LONGITUDE = "indicates the longitude of the location on the world map"


class SubPagesArticle(models.Model):
    title = models.CharField(max_length=40, help_text="Enter a titles article")
    address = models.CharField(max_length=40, help_text=SUBPAGESARTICLE_ADDRESS,
                               null=True, blank=True)
    section = models.ForeignKey('SubPagesSection', on_delete=models.SET_NULL,
                                related_name='content', null=True, blank=True)
    body = HTMLField(help_text="Enter a text article", null=True, blank=True)
    uniq_template = models.BooleanField(default=False, help_text=SUBPAGESARTICLE_UNIQ_TEMPLATE)

    def __str__(self):
        return self.address

    def get_absolute_url(self):
        return reverse('app_shop:subpage_allhere_in_russia', args=[self.address])

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.address:
            self.address = transliterate(self.title)
        return super(SubPagesArticle, self).save()

    class Meta:
        verbose_name = 'SubPages Article'
        verbose_name_plural = 'SubPages Articles'


class SubPagesSection(models.Model):
    title = models.CharField(max_length=30, help_text="Enter a sections of articles")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'SubPages Section'
        verbose_name_plural = 'SubPages Sections'


class Shops(models.Model):
    name = models.CharField(max_length=40, help_text="Enter store name")
    city = models.CharField(max_length=20, choices=constants.CITY_LIST, help_text=SHOPS_CITY)
    address = models.CharField(max_length=100, help_text=SHOPS_ADDRESS)
    type = models.ForeignKey('ShopType', on_delete=models.SET_NULL, related_name='content',
                             null=True, blank=True)
    description = HTMLField(help_text="Enter a store description", null=True, blank=True)
    latitude = models.DecimalField(help_text=SHOPS_LATITUDE, max_digits=10, decimal_places=7,
                                   editable=False, null=True, blank=True)
    longitude = models.DecimalField(help_text=SHOPS_LONGITUDE, max_digits=10, decimal_places=7,
                                    editable=False, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('allhere_in_russia:shop_detail', args=[self.id])

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        client = Client("%s" % settings.API_KEY_YANDEX_GEOCODER)
        coordinates = client.coordinates(self.address)
        self.latitude = coordinates[0]
        self.longitude = coordinates[1]
        return super(Shops, self).save()

    class Meta:
        ordering = ['city', 'type', 'name']
        verbose_name = 'Shop'
        verbose_name_plural = 'Shops'


class ShopType(models.Model):
    title = models.CharField(max_length=30, help_text="Enter a type of shop")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'ShopType'
        verbose_name_plural = 'ShopsType'


class News(models.Model):
    title = models.CharField(max_length=100, help_text="Enter a news titles")
    body = HTMLField(help_text="Enter a news text")
    datetime = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('allhere_in_russia:news', args=[self.id])

    class Meta:
        ordering = ['datetime', 'title']
        verbose_name = 'News'
        verbose_name_plural = 'News'

allhere_in_russia/forms.py
from django import forms


class ApplicationForOrderingForm(forms.Form):
    the_contact_person = forms.CharField(label="Контактное лицо", max_length=100)
    tin_of_the_organization = forms.CharField(label="ИНН Организации")
    email = forms.EmailField(label="E-mail", max_length=40)
    contact_phone_number = forms.CharField(label="Номер телефона для связи", initial="+7")
    order_list = forms.CharField(
        label="Состав заказа (список и количество позиций)",
        max_length=1000,
        help_text="Сумма заказа должна быть от 50 000 рублей",
        widget=forms.Textarea(attrs={'rows': 4})
    )


TYPE_SENTENCE = (
    ('rr', 'Аренда помещения'),
    ('sr', 'Продажа помещения'),
    ('sl', 'Продажа земельного участка'),
    ('ot', 'Иное'),
)


class ForLandlordsForm(forms.Form):
    type_sentence = forms.ChoiceField(label="Тип предложения", choices=TYPE_SENTENCE)
    region = forms.CharField(label="Регион", max_length=60)
    town = forms.CharField(label="Город", max_length=20)
    street_house = forms.CharField(label="Улица, дом", max_length=30)
    map_link = forms.CharField(
        label="Ссылка на карту или файл с указанием месторасположения участка или объекта:",
        help_text="необязательное для заполнения поле",
        required=False
    )
    land_area = forms.CharField(
        label="Предлагаемая площадь помещения/земельного участка:",
        max_length=20
    )
    land_cadastral_number = forms.CharField(
        label="Кадастровый номер земельного участка",
        help_text="необязательное для заполнения поле",
        required=False
    )
    contact_person = forms.CharField(label="Ф.И.О. контактного лица", max_length=50)
    contact_telephone = forms.CharField(label="Телефонный номер контактного лица", max_length=15)
    contact_email = forms.EmailField(label="E-mail контактного лица", max_length=30)
    additional_information = forms.CharField(
        label="Дополнительная информация",
        max_length=600,
        help_text="Текст не более 600 символов, для больших обьёмов текста воспользуйтесь функцией загрузки файла ниже",
        required=False,
        widget=forms.Textarea(attrs={'rows': 4})
    )
    file = forms.FileField(label="Вложение", required=False)


class ForLeaseHoldersForm(forms.Form):
    contact_person = forms.CharField(label="Ф.И.О. контактного лица", max_length=50)
    contact_telephone = forms.CharField(label="Телефонный номер контактного лица", max_length=15)
    contact_fax = forms.CharField(
        label="Факс контактного лица",
        max_length=15,
        help_text="необязательное для заполнения поле",
        required=False
    )
    contact_email = forms.EmailField(label="E-mail контактного лица", max_length=30)
    contact_website = forms.CharField(
        label="Сайт контактного лица",
        max_length=25,
        help_text="необязательное для заполнения поле",
        required=False
    )
    company_name = forms.CharField(label="Название компании", max_length=50)
    brand = forms.CharField(label="Торговая марка/Название магазина", max_length=50)
    description_company = forms.CharField(
        label="Краткое описание деятельности компании",
        max_length=500,
        help_text="Текст не более 500 символов",
        widget=forms.Textarea(attrs={'rows': 3})
    )
    presented_tm = forms.CharField(
        label="Представленные торговые марки",
        max_length=300,
        help_text="Текст не более 300 символов",
        widget=forms.Textarea(attrs={'rows': 3})
    )
    current_stores = forms.CharField(
        label="Информация о действующих магазинах сети с указанием адреса",
        max_length=300,
        help_text="Текст не более 300 символов",
        widget=forms.Textarea(attrs={'rows': 3})
    )
    network_develops = forms.CharField(
        label="Если сеть развивает разные форматы, пожалуйста, укажите их",
        max_length=300, help_text="Текст не более 300 символов",
        widget=forms.Textarea(attrs={'rows': 3})
    )
    development_plans = forms.CharField(
        label="Планы развития сети", max_length=300,
        help_text="Текст не более 300 символов",
        widget=forms.Textarea(attrs={'rows': 3})
    )
    interested_region = forms.CharField(
        label="Какой город/регион Вас интересует?",
        max_length=100,
        help_text="Текст не более 100 символов",
        widget=forms.Textarea(attrs={'rows': 1})
    )
    competitor_store = forms.CharField(
        label="Кого вы считаете прямым конкурентом магазина, сети?",
        max_length=100,
        help_text="Текст не более 100 символов",
        widget=forms.Textarea(attrs={'rows': 1})
    )
    favorable_neighborhood = forms.CharField(
        label="Соседство с каким профилем, магазином какого вида деятельности для вас наиболее благоприятно?",
        max_length=100,
        help_text="Текст не более 100 символов",
        widget=forms.Textarea(attrs={'rows': 1})
    )
    price_range = forms.CharField(
        label="Укажите ценовой диапазон товаров, представленных в магазинах сети",
        max_length=100,
        help_text="Текст не более 100 символов",
        widget=forms.Textarea(attrs={'rows': 1})
    )
    kind_of_consumer = forms.CharField(
        label="На какого потребителя рассчитан магазин, сеть?",
        max_length=100,
        help_text="Текст не более 100 символов",
        widget=forms.Textarea(attrs={'rows': 1})
    )
    required_footage = forms.CharField(
        label="Необходимый метраж помещения (минимальный, максимальный, оптимальный)",
        max_length=50
    )
    technical_requirements = forms.CharField(
        label="Уточните технические требования (по электроэнергии, воде, др.)",
        max_length=300,
        help_text="Текст не более 300 символов",
        widget=forms.Textarea(attrs={'rows': 3})
    )


SELECT_REGION = (
    ('ekt', 'Екатеринбург'),
    ('knd', 'Краснодар'),
    ('mos', 'Москва'),
    ('nng', 'Нижний Новгород'),
    ('sam', 'Самара'),
    ('spb', 'Санкт-Петербург')
)


class CardApplicationForm(forms.Form):
    region = forms.ChoiceField(label="Регион", choices=SELECT_REGION, initial="mos")
    user_name = forms.CharField(label="Ф.И.О", max_length=60)
    user_phone = forms.CharField(label="Номер телефона", max_length=20)

allhere_in_russia/views.py
from contextlib import suppress

from django.views import generic

from .models import News, Shops, SubPagesArticle


class SubpageAboutCompanyView(generic.DetailView):
    model = SubPagesArticle
    slug_field = 'address'
    slug_url_kwarg = 'address'

    def get_template_names(self):
        if self.object.uniq_template:
            return 'uniq/%s.html' % self.object.address
        return '%s.html' % self.object.section


class ShopDetailView(generic.DetailView):
    model = Shops
    template_name = 'uniq/shop_detail.html'
    slug_field = 'id'
    slug_url_kwarg = 'id'


class NewsDetailView(generic.DetailView):
    model = News
    template_name = 'allhere_news.html'
    slug_field = 'id'
    slug_url_kwarg = 'id'

    def get_object(self, queryset=None):
        with suppress(AttributeError):
            return super().get_object()
        return News.objects.all().first()

    def get_context_data(self, **kwargs):
        return {
            'news_list': News.objects.all(),
            **super().get_context_data()
        }

allhere_in_russia/templates/about_allhere.html
{% extends "allhere_in_russia.html" %}


{% block title %}
<title>AllHere в России | {{ object.title }}</title>
{% endblock %}

{% block sub-navigation %}
<ul class="navbar-nav flex-row align-items-center w-50">
  <li class="nav-item flex-fill">
    <div class="dropdown text-center">
      <a class="dropdown-toggle p-0" type="button" id="dropdownMenuAboutCompany" data-toggle="dropdown"
         aria-haspopup="true" aria-expanded="false">О компании</a>
      <div class="dropdown-menu position-absolute" aria-labelledby="dropdownMenuAboutCompany">
        <a class="dropdown-item"
           href="{% url 'allhere_in_russia:subpages' 'allhere_in_russia' %}">AllHere в России</a>
      </div>
    </div>
  </li>
  <li class="nav-item flex-fill">
    <div class="dropdown text-center">
      <a class="dropdown-toggle p-0" type="button" id="dropdownMenuQuality" data-toggle="dropdown" aria-haspopup="true"
         aria-expanded="false">Качество AllHere</a>
      <div class="dropdown-menu position-absolute" aria-labelledby="dropdownMenuQuality">
        <a class="dropdown-item"
           href="{% url 'allhere_in_russia:subpages' 'quality_department' %}">Отдел качества</a>
        <a class="dropdown-item"
           href="{% url 'allhere_in_russia:subpages' 'sanitary_safety' %}">Санитарная безопасность</a>
      </div>
    </div>
  </li>
  <li class="nav-item flex-fill">
    <div class="dropdown text-center">
      <a class="btn dropdown-toggle p-0" type="button" id="dropdownMenuProjects" data-toggle="dropdown"
         aria-haspopup="true" aria-expanded="false">Проекты AllHere</a>
      <div class="dropdown-menu position-absolute" aria-labelledby="dropdownMenuProjects">
        <a class="dropdown-item"
           href="{% url 'allhere_in_russia:subpages' 'allhere_garden' %}">AllHere Сад</a>
        <a class="dropdown-item"
           href="{% url 'allhere_in_russia:subpages' 'allhere_city' %}">AllHere Сити</a>
        <a class="dropdown-item"
           href="{% url 'allhere_in_russia:subpages' 'charitable_foundation' %}">Благотворительный фонд "Поколение AllHere"</a>
        <a class="dropdown-item"
           href="{% url 'allhere_in_russia:subpages' 'сollateral_trolley_system' %}">Залоговая система для тележек</a>
      </div>
    </div>
  </li>
</ul>
{% endblock %}

{% block content %}
<div class="content-block__text-block">
{{ object.body|safe }}
</div>
{% endblock %}

allhere_in_russia/templates/allhere_in_russia.html
<!DOCTYPE html>


{% load static %}
{% load crispy_forms_tags %}

<html lang="en">
<head>

  {% block title %}<title>AllHere в России</title>{% endblock %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="SHORTCUT ICON" href="{% static 'favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles_about.css' %}">
  <script src="//code.jquery.com/jquery-3.5.1.slim.min.js"
          integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
          crossorigin="anonymous"></script>
  <script src="//cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
          integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
          crossorigin="anonymous"></script>
  <script src="//stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
          integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
          crossorigin="anonymous"></script>
  <script src="//api-maps.yandex.ru/2.1/?apikey={{ API_KEY_YANDEX_GEOCODER }}&lang=ru_RU&load=Geolink"
          type="text/javascript"></script>

</head>

<body>
  <div class="container-block container">
    <!-- header -->
    <header class="header-block header">
      <nav class="header-block__primary-header navbar">
        <div class="navbar ml-auto h-100 py-0">
          <ul class="navbar-nav flex-row align-items-center h-100">
            <li class="nav-item d-flex align-items-center h-100 mr-3">
              <a class="nav-link p-0" href="{% url 'app_shop:main_sub_pages' 'service' %}">Доставка</a>
            </li>
            <li class="nav-item d-flex align-items-center h-100 mr-3">
              <a class="nav-link p-0" href="{% url 'app_shop:main_sub_pages' 'service' %}">Оплата</a>
            </li>
            <li class="nav-item d-flex align-items-center h-100 mr-3">
              <a class="nav-link p-0" href="{% url 'allhere_in_russia:subpages' 'tenants_and_landlords' %}">Аренда</a>
            </li>
          </ul>
        </div>
      </nav>
      <div class="header-block__secondary-header d-flex align-items-center justify-content-center">
        <div class="logo-block d-flex align-items-end justify-content-center mr-md-5 ml-md-5">
          <a class="stretched-link" href="{% url 'app_shop:main_sub_pages' %}"></a>
          <p class="logo-block_text text-center invisible">Перейти в магазин</p>
        </div>
      </div>
    </header>
    <!-- header end -->
    <!-- navigation -->
    <div class="navigation-block container p-0">
      <nav class="navbar navbar-light bg-light p-0">
        <ul class="navbar-nav flex-row w-100">
          <li class="nav-item flex-fill">
            <div class="navigation-block__item-first position-relative">
              <a class="stretched-link" href="{% url 'app_shop:main_sub_pages' %}"></a>
              <p class="text-center">Интернет-магазин</p>
            </div>
          </li>
          <li class="nav-item flex-fill active">
            <div class="navigation-block__item position-relative">
              <a class="stretched-link" href="{% url 'allhere_in_russia:subpages' 'all_shops' %}"></a>
              <p class="text-center">Ваш магазин</p>
            </div>
          </li>
          <li class="nav-item flex-fill">
            <div class="navigation-block__item position-relative">
              <a class="stretched-link" href="{% url 'allhere_in_russia:subpages' 'allhere_in_russia' %}"></a>
              <p class="text-center">Об AllHere</p>
            </div>
          </li>
          <li class="nav-item flex-fill">
            <div class="navigation-block__item position-relative">
              <a class="stretched-link" href="{% url 'allhere_in_russia:subpages' 'advantages' %}"></a>
              <p class="text-center">Работа в AllHere</p>
            </div>
          </li>
          <li class="nav-item flex-fill">
            <div class="navigation-block__item position-relative">
              <a class="stretched-link" href="{% url 'app_shop:main_sub_pages' 'for_wholesalers'%}"></a>
              <p class="text-center">Оптовикам</p>
            </div>
          </li>
          <li class="nav-item flex-fill">
            <div class="navigation-block__item position-relative">
              <a class="stretched-link" href="#"></a>
              <p class="text-center">Поставщикам</p>
            </div>
          </li>
          <li class="nav-item flex-fill">
            <div class="navigation-block__item-last position-relative">
              <div class="dropdown dropup text-center">
                <a class="dropdown-toggle p-0" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                  Личный кабинет
                </a>
                <div class="dropdown-menu border-danger position-absolute" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item text-center" href="{% url 'app_shop:authentication' %}">Войти</a>
                  <a class="dropdown-item text-center" href="{% url 'app_shop:authentication' %}">Зарегистрироваться</a>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </nav>
    </div>
    <!-- navigation end -->
    <!-- sub-navigation -->
    <div class="sub-navigation-block container">
      <nav class="navbar navbar-light bg-light p-0">
        {% block sub-navigation %}
        {% endblock %}
      </nav>
      <div class="sub-navigation-block__name-page">
        <p class="sub-navigation-block__name-text">
          {% block name-page %}
          {{ object.title }}
          {% endblock %}
        </p>
      </div>
    </div>
    <!-- sub-navigation end -->
    <!-- content -->
    <div class="content-block">
      {% block content %}
      {% endblock %}
    </div>
    <!-- content end -->
    <!-- footer -->
    <footer class="footer-block container p-0">
      <nav class="footer-block__nav navbar py-0">
        <ul class="navbar-nav flex-row align-items-center text-center w-50">
          <li class="nav-item flex-fill">
            <a class="nav-link p-0" href="{% url 'allhere_in_russia:subpages' 'feedback' %}">
              Обратная связь
            </a>
          </li>
          <li class="nav-item flex-fill">
            <a class="nav-link p-0" href="{% url 'allhere_in_russia:news' %}">
              Новости
            </a>
          </li>
          <li class="nav-item flex-fill">
            <a class="nav-link p-0" href="#">
              Политика конфиденциальности
            </a>
          </li>
        </ul>
      </nav>
    </footer>
    <!-- footer end -->
  </div>
</body>
</html>

allhere_in_russia/templates/allhere_rent.html
{% extends "allhere_in_russia.html" %}


{% block title %}
<title>AllHere в России | {{ object.title }}</title>
{% endblock %}

{% block name-page %}
{{ object.title }}
{% endblock %}

{% block content %}
<div class="col-11 m-auto py-3">
  {{ object.body|safe }}
  <div class="d-flex justify-content-center py-2">
    <div class="btn-group w-100" role="group" aria-label="Basic example">
      <a class="rent-button btn btn-warning" role="button"
         href="{% url 'allhere_in_russia:subpages' 'for_leaseholders' %}">Анкета для арендатора</a>
      <a class="rent-button btn btn-warning" role="button"
         href="{% url 'allhere_in_russia:subpages' 'for_landlords' %}">Анкета для арендодатора</a>
    </div>
  </div>
</div>
{% endblock %}

allhere_in_russia/templates/allhere_shops.html
{% extends "allhere_in_russia.html" %}


{% block title %}
  <title>Наши магазины</title>
{% endblock %}

{% block sub-navigation %}
  <ul class="navbar-nav flex-row align-items-center w-100">
    <li class="nav-item flex-fill">
      <p class="text-center">Выберите ближайший к вам магазин</p>
    </li>
    <li class="nav-item flex-fill">
      <div class="dropdown text-center">
        <a class="dropdown-toggle p-0" type="button" id="dropdownMenuShopsAllHere" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          AllHere
        </a>
        <div class="dropdown-menu position-absolute" aria-labelledby="dropdownMenuShopsAllHere">
          {% for item in shops_list %}
            {% if item.type.title == 'AllHere' %}
              <a class="dropdown-item {% if item.id == request.session.shop %}bg-success text-white{% endif %}"
                 href="{% url 'allhere_in_russia:shop_detail' item.id %}">{{ item.get_city_display }} / {{ item.name }}</a>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    </li>
    <li class="nav-item flex-fill">
      <div class="dropdown text-center">
        <a class="dropdown-toggle p-0" type="button" id="dropdownMenuShopsAllHereGarden" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          AllHere Сад
        </a>
        <div class="dropdown-menu position-absolute" aria-labelledby="dropdownMenuShopsAllHereGarden">
          {% for item in shops_list %}
            {% if item.type.title == 'AllHere Сад' %}
              <a class="dropdown-item {% if item.id == request.session.shop %}bg-success text-white{% endif %}"
                 href="{% url 'allhere_in_russia:shop_detail' item.id %}">{{ item.get_city_display }} / {{ item.name }}</a>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    </li>
    <li class="nav-item flex-fill">
      <div class="dropdown text-center">
        <a class="dropdown-toggle p-0" type="button" id="dropdownMenuShopsAllHereCity" data-toggle="dropdown"
           aria-haspopup="true" aria-expanded="false">
          AllHere Сити
        </a>
        <div class="dropdown-menu position-absolute" aria-labelledby="dropdownMenuShopsAllHereCity">
          {% for item in shops_list %}
            {% if item.type.title == 'AllHere Сити' %}
              <a class="dropdown-item {% if item.id == request.session.shop %}bg-success text-white{% endif %}"
                 href="{% url 'allhere_in_russia:shop_detail' item.id %}">{{ item.get_city_display }} / {{ item.name }}</a>
            {% endif %}
          {% endfor %}
        </div>
      </div>
    </li>
  </ul>
{% endblock %}

{% block content %}
  {% block map %}
  {% endblock %}
  <div class="content-block__city-list col-11 col-md-4">
    <h4 class="text-center">Наши магазины можно найти в городах:</h4>
    <div class="row justify-content-center">
      <div class="col-8 my-2">
        {% for city in city_list %}
          <p>{{ city }}</p>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}