allhere_in_russia/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views


app_name = 'allhere_in_russia'
urlpatterns = [
    url(r'^$', RedirectView.as_view(url='allhere_in_russia', permanent=False), name='subpage_index'),
    url(r'^(?P<address>\w+)$', views.SubpageAboutCompanyView.as_view(), name='subpages'),
    url(r'^all_shops/(?P<id>\w+)$', views.ShopDetailView.as_view(), name='shop_detail'),
    url(r'^news/(?P<id>\w+)?$', views.NewsDetailView.as_view(), name='news'),
]

app_shop/urls.py
from django.conf.urls import url
from django.urls import include

from . import views


authentication = [
    url(r'^login$', views.authentication, name='authentication'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^registration$', views.registration, name='registration'),
    url(r'^user_account$', views.user_account, name='user_account'),
]

shopping = [
    url(r'^product/(?P<slug>\S+)$', views.ProductDetailView.as_view(), name='product_detail'),
    url(r'^category/(?P<category_id>\S+)$', views.CategoryListView.as_view(), name='section_products'),
    url(r'^change_user_shop/(?P<shop_id>\w+)$', views.change_user_shop, name='change_user_shop'),
    url(r'^search$', views.search, name='search'),
]

cart = [
    url(r'^$', views.cart, name='cart'),
    url(r'^add_product/(?P<product_id>\w+)$', views.add_product_to_cart, name='add_product'),
    url(r'^remove_from_cart/(?P<product_id>\w+)$', views.remove_product_from_cart, name='remove_product'),
    url(r'^remove_one_from_cart/(?P<product_id>\w+)$', views.remove_one_from_cart, name='remove_one_copy'),
    url(r'^empty_trash/', views.empty_trash, name='empty_trash'),
    url(r'^send_order$', views.send_order, name='send_order'),
]

app_name = 'app_shop'
urlpatterns = [
    url(r'^subscription$', views.subscription, name='subscription'),
    url(r'^auth/', include(authentication)),
    url(r'^cart/', include(cart)),
    url(r'^shopping/', include(shopping)),
    url(r'^(?P<page>\w+)?$', views.main_sub_pages, name='main_sub_pages'),
]

shop_allhere/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

from app_shop import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('allhere.ru/', include('app_shop.urls')),
    path('allhere_in_russia/', include('allhere_in_russia.urls')),
    path('', RedirectView.as_view(url='/allhere.ru/', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = views.handler403
handler404 = views.handler404
handler500 = views.handler500

allhere_in_russia/models.py
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField
from yandex_geocoder import Client

from shop_allhere import constants, settings
from shop_allhere.utils import transliterate


SUBPAGESARTICLE_ADDRESS = "Enter a url address for article, otherwise the address will be set automatically"
SUBPAGESARTICLE_UNIQ_TEMPLATE = "check if the page will use a unique HTML template"
SHOPS_CITY = "Check the city where the store is located"
SHOPS_ADDRESS = "Enter address of shop in the format City, street, house number"
SHOPS_LATITUDE = "indicates the latitude of the location on the world map"
SHOPS_LONGITUDE = "indicates the longitude of the location on the world map"


class SubPagesArticle(models.Model):
    title = models.CharField(max_length=40, help_text="Enter a titles article")
    address = models.CharField(max_length=40, help_text=SUBPAGESARTICLE_ADDRESS,
                               null=True, blank=True)
    section = models.ForeignKey('SubPagesSection', on_delete=models.SET_NULL,
                                related_name='content', null=True, blank=True)
    body = HTMLField(help_text="Enter a text article", null=True, blank=True)
    uniq_template = models.BooleanField(default=False, help_text=SUBPAGESARTICLE_UNIQ_TEMPLATE)

    def __str__(self):
        return self.address

    def get_absolute_url(self):
        return reverse('app_shop:subpage_allhere_in_russia', args=[self.address])

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.address:
            self.address = transliterate(self.title)
        return super(SubPagesArticle, self).save()

    class Meta:
        verbose_name = 'SubPages Article'
        verbose_name_plural = 'SubPages Articles'


class SubPagesSection(models.Model):
    title = models.CharField(max_length=30, help_text="Enter a sections of articles")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'SubPages Section'
        verbose_name_plural = 'SubPages Sections'


class Shops(models.Model):
    name = models.CharField(max_length=40, help_text="Enter store name")
    city = models.CharField(max_length=20, choices=constants.CITY_LIST, help_text=SHOPS_CITY)
    address = models.CharField(max_length=100, help_text=SHOPS_ADDRESS)
    type = models.ForeignKey('ShopType', on_delete=models.SET_NULL, related_name='content',
                             null=True, blank=True)
    description = HTMLField(help_text="Enter a store description", null=True, blank=True)
    latitude = models.DecimalField(help_text=SHOPS_LATITUDE, max_digits=10, decimal_places=7,
                                   editable=False, null=True, blank=True)
    longitude = models.DecimalField(help_text=SHOPS_LONGITUDE, max_digits=10, decimal_places=7,
                                    editable=False, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('allhere_in_russia:shop_detail', args=[self.id])

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        client = Client("%s" % settings.API_KEY_YANDEX_GEOCODER)
        coordinates = client.coordinates(self.address)
        self.latitude = coordinates[0]
        self.longitude = coordinates[1]
        return super(Shops, self).save()

    class Meta:
        ordering = ['city', 'type', 'name']
        verbose_name = 'Shop'
        verbose_name_plural = 'Shops'


class ShopType(models.Model):
    title = models.CharField(max_length=30, help_text="Enter a type of shop")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'ShopType'
        verbose_name_plural = 'ShopsType'


class News(models.Model):
    title = models.CharField(max_length=100, help_text="Enter a news titles")
    body = HTMLField(help_text="Enter a news text")
    datetime = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('allhere_in_russia:news', args=[self.id])

    class Meta:
        ordering = ['datetime', 'title']
        verbose_name = 'News'
        verbose_name_plural = 'News'

app_shop/models/information.py
from django.db import models


class SubscriptionEmails(models.Model):
    email = models.EmailField(max_length=40, help_text="Enter email for mailing", unique=True)

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = 'Mailing address'
        verbose_name_plural = 'Postal addresses'


class VisitStatistics(models.Model):
    url_address = models.CharField(max_length=200)
    user_id = models.PositiveSmallIntegerField(null=True, blank=True)
    actions = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.id

    class Meta:
        verbose_name = 'Page visit'
        verbose_name_plural = 'Page visits'

app_shop/models/information_models.py
from django.db import models


class SubscriptionEmails(models.Model):
    email = models.EmailField(max_length=40, help_text="Enter email for mailing", unique=True)

    def __str__(self):
        return self.email

    class Meta:
        app_label = 'app_shop'
        verbose_name = 'Mailing address'
        verbose_name_plural = 'Postal addresses'


class VisitStatistics(models.Model):
    url_address = models.CharField(max_length=200)
    user_id = models.PositiveSmallIntegerField(null=True, blank=True)
    actions = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.id

    class Meta:
        app_label = 'app_shop'
        verbose_name = 'Page visit'
        verbose_name_plural = 'Page visits'

allhere_in_russia/views.py
from contextlib import suppress

from django.views import generic

from .models import News, Shops, SubPagesArticle


class SubpageAboutCompanyView(generic.DetailView):
    model = SubPagesArticle
    slug_field = 'address'
    slug_url_kwarg = 'address'

    def get_template_names(self):
        if self.object.uniq_template:
            return 'uniq/%s.html' % self.object.address
        return '%s.html' % self.object.section


class ShopDetailView(generic.DetailView):
    model = Shops
    template_name = 'uniq/shop_detail.html'
    slug_field = 'id'
    slug_url_kwarg = 'id'


class NewsDetailView(generic.DetailView):
    model = News
    template_name = 'allhere_news.html'
    slug_field = 'id'
    slug_url_kwarg = 'id'

    def get_object(self, queryset=None):
        with suppress(AttributeError):
            return super().get_object()
        return News.objects.all().first()

    def get_context_data(self, **kwargs):
        return {
            'news_list': News.objects.all(),
            **super().get_context_data()
        }

app_shop/views/handlers_errors.py
from django.shortcuts import render


def handler403(request, *args, **kwargs):
    return render(request, 'handlers/403.html', status=403)


def handler404(request, *args, **kwargs):
    return render(request, 'handlers/404.html', status=404)


def handler500(request, *args, **kwargs):
    return render(request, 'handlers/500.html', status=500)

app_shop/views/site_function.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render

from app_shop.forms import SearchForm, SubscriptionForm
from app_shop.models import Product, ProductClassification, SubscriptionEmails


def search(request):
    form = SearchForm(request.GET)
    if not form.is_valid():
        return HttpResponseRedirect(request.path)

    key = form.cleaned_data.get("search_key")
    object_list = Product.objects.filter(Q(name__icontains=key) | Q(description__icontains=key))
    category_ids = object_list.values_list('classification_id', flat=True)
    category_list = ProductClassification.objects.filter(id__in=category_ids)
    return render(
        request,
        'search_results.html',
        context={
            'object_list': object_list,
            'key': key,
            'category_list': category_list
            }
    )


def subscription(request):
    form = SubscriptionForm(request.POST)
    if not form.is_valid():
        return redirect(request.GET['next'])

    SubscriptionEmails.objects.get_or_create(**form.cleaned_data)
    return redirect(request.GET['next'])

app_shop/views/site_rendering.py
from django.db.models import Count, Max, Min, Subquery, OuterRef
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic

from app_shop.forms import PriceForm, FiltersForm
from app_shop.models import (
    ClassificationFilters, FiltersForClassifications, Promotions,
    Product, ProductClassification, ProductListForOrder, ProductQuantity
)
from shop_allhere.utils import get_promotions_for_category


def main_sub_pages(request, **kwargs):
    context_content = {}
    if not kwargs:
        template_name = 'index.html'
        context_content['promotions_for_carousel'] = Promotions.objects.filter(for_carousel=True)
        context_content['highest_categories'] = ProductClassification.objects.filter(highest_category=True)
    else:
        template_name = 'main_subpages/%s.html' % kwargs['page']

    context_content['promotions_ordinary'] = list(Promotions.objects.filter(
        for_category=None, for_carousel=False).order_by('?')[:5])
    return render(request, template_name, context={**context_content})


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'product_detail.html'

    def get_context_data(self, **kwargs):
        self.object.count = (ProductQuantity.objects.get(
            shop_id=self.request.session['shop'], product_id=self.object.id)).number

        list_orders_id = ProductListForOrder.objects.filter(
            product_id=self.object.id).values_list('orderlist_id', flat=True)
        most_often_buy = ProductListForOrder.objects.filter(
            orderlist_id__in=list_orders_id).exclude(product_id=self.object.id).values('product_id').annotate(
            count=Count("id")).order_by('-count')[:5]
        most_often_buy = most_often_buy.values_list('product_id', flat=True)
        also_buy_products = Product.objects.filter(id__in=most_often_buy)

        similiar_products = Product.objects.filter(
            classification=self.object.classification).exclude(
            id=self.object.id).order_by('?')[:5]

        promotions_for_page = get_promotions_for_category([self.object.classification_id])

        context = {
            'also_buy_products': also_buy_products,
            'similiar_products': similiar_products,
            'promotions_for_page': promotions_for_page,
            **kwargs
        }
        return super().get_context_data(**context)


class CategoryListView(generic.ListView):
    model = ProductClassification
    template_name = 'section_products.html'

    def get_queryset(self):
        query_dictionary = {}
        order = self.request.GET.get('sorted', None)
        if order not in ['price', '-price']:
            order = 'name'

        if self.kwargs:
            filters_form = FiltersForm(self.request.GET)
            if not filters_form.is_valid():
                return HttpResponseRedirect(self.request.path)

            for filter_key, filter_value in filters_form.data.items():
                if filter_key != 'price' and filter_value:
                    filter_obj = FiltersForClassifications.objects.filter(name=filter_key).first()
                    if filter_obj:
                        if filter_obj.type == "INT":
                            query_dictionary['specifications__' + filter_key + '__lte'] = float(filter_value)
                        elif filter_obj.type == "CSM":
                            query_dictionary['specifications__' + filter_key + '__in'] = self.request.GET.getlist(filter_key)
                elif filter_value:
                    query_dictionary['the_final_price__lte'] = float(filter_value)

        def recursive_get_childs(item):
            yield item.id
            for child in item.get_child():
                yield from recursive_get_childs(child)

        self.kwargs['category'] = ProductClassification.objects.get(id=self.kwargs['category_id'])
        self.kwargs['category_ids'] = list(recursive_get_childs(self.kwargs['category']))
        query_dictionary['classification_id__in'] = self.kwargs['category_ids']

        products_quantity = ProductQuantity.objects.filter(
            shop_id=self.request.session['shop'],
            product_id=OuterRef('id')
        )
        self.queryset = Product.objects.filter(**query_dictionary).order_by('classification', order).annotate(
            count=Subquery(products_quantity.values_list('number', flat=True)[:1])
        )
        return self.queryset

    def get_context_data(self, **kwargs):
        form_dictionary = {}

        self.kwargs['category_ids'] = self.queryset.values_list('classification_id', flat=True)

        promotions_for_page = get_promotions_for_category(self.kwargs['category_ids'])
        product_listing_ads = Promotions.objects.select_related('advertising').filter(
            advertising__obligatory=True).order_by("?")[:5]

        price_values = self.queryset.aggregate(
            min_price=Min('the_final_price'), max_price=Max('the_final_price'))
        price_form = PriceForm(min_value=price_values['min_price'])
        form_dictionary['price_form'] = price_form

        filter_list = ClassificationFilters.objects.filter(
            classification_id=self.kwargs['category_id']).values('filter__name', 'filter__type', 'filter__priority')

        form_filters = []
        for filter_object in filter_list:
            if filter_object['filter__type'] != 'TXT':
                value = self.queryset.values_list('specifications__' + filter_object['filter__name'], flat=True)
                if filter_object['filter__type'] == 'INT':
                    filter_object['filter__values'] = [min(value), max(value)]
                elif filter_object['filter__type'] == 'CSM':
                    filter_object['filter__values'] = value
            form_filters.append(filter_object)

        filters_form = FiltersForm(filters=form_filters)
        form_dictionary['filters_form'] = filters_form

        context = {
            'category': self.kwargs['category'],
            'promotions_for_page': promotions_for_page,
            'product_listing_ads': product_listing_ads,
            'price_values': price_values,
            **form_dictionary,
            **kwargs,
        }
        return super().get_context_data(**context)

app_shop/templates/subpage_allhere_in_russia/allhere_in_russia.html
<!DOCTYPE html>


{% load static %}
{% load crispy_forms_tags %}

<html lang="en">
<head>

  {% block title %}<title>AllHere в России</title>{% endblock %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="SHORTCUT ICON" href="{% static 'favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles_about.css' %}">
  <script src="//code.jquery.com/jquery-3.5.1.slim.min.js"
          integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
          crossorigin="anonymous"></script>
  <script src="//cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
          integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
          crossorigin="anonymous"></script>
  <script src="//stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
          integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
          crossorigin="anonymous"></script>
  <script src="//api-maps.yandex.ru/2.1/?apikey={{ API_KEY_YANDEX_GEOCODER }}&lang=ru_RU&load=Geolink"
          type="text/javascript"></script>

</head>

<body>
  <div class="container-block container">
    <!-- header -->
    <header class="header-block header">
      <nav class="header-block__primary-header navbar">
        <div class="navbar ml-auto h-100 py-0">
          <ul class="navbar-nav flex-row align-items-center h-100">
            <li class="nav-item d-flex align-items-center h-100 mr-3">
              <a class="nav-link p-0" href="{% url 'app_shop:main_sub_pages' 'service' %}">Доставка</a>
            </li>
            <li class="nav-item d-flex align-items-center h-100 mr-3">
              <a class="nav-link p-0" href="{% url 'app_shop:main_sub_pages' 'service' %}">Оплата</a>
            </li>
            <li class="nav-item d-flex align-items-center h-100 mr-3">
              <a class="nav-link p-0" href="{% url 'app_shop:subpage_allhere_in_russia' 'tenants_and_landlords' %}">Аренда</a>
            </li>
          </ul>
        </div>
      </nav>
      <div class="header-block__secondary-header d-flex align-items-center justify-content-center">
        <div class="logo-block d-flex align-items-end justify-content-center mr-md-5 ml-md-5">
          <a class="stretched-link" href="{% url 'app_shop:index' %}"></a>
          <p class="logo-block_text text-center invisible">Перейти в магазин</p>
        </div>
      </div>
    </header>
    <!-- header end -->
    <!-- navigation -->
    <div class="navigation-block container p-0">
      <nav class="navbar navbar-light bg-light p-0">
        <ul class="navbar-nav flex-row w-100">
          <li class="nav-item flex-fill">
            <div class="navigation-block__item-first position-relative">
              <a class="stretched-link" href="{% url 'app_shop:index' %}"></a>
              <p class="text-center">Интернет-магазин</p>
            </div>
          </li>
          <li class="nav-item flex-fill active">
            <div class="navigation-block__item position-relative">
              <a class="stretched-link" href="{% url 'app_shop:subpage_allhere_in_russia' 'all_shops' %}"></a>
              <p class="text-center">Ваш магазин</p>
            </div>
          </li>
          <li class="nav-item flex-fill">
            <div class="navigation-block__item position-relative">
              <a class="stretched-link" href="{% url 'app_shop:subpage_allhere_in_russia' 'allhere_in_russia' %}"></a>
              <p class="text-center">Об AllHere</p>
            </div>
          </li>
          <li class="nav-item flex-fill">
            <div class="navigation-block__item position-relative">
              <a class="stretched-link" href="{% url 'app_shop:subpage_allhere_in_russia' 'advantages' %}"></a>
              <p class="text-center">Работа в AllHere</p>
            </div>
          </li>
          <li class="nav-item flex-fill">
            <div class="navigation-block__item position-relative">
              <a class="stretched-link" href="{% url 'app_shop:main_sub_pages' 'for_wholesalers'%}"></a>
              <p class="text-center">Оптовикам</p>
            </div>
          </li>
          <li class="nav-item flex-fill">
            <div class="navigation-block__item position-relative">
              <a class="stretched-link" href="#"></a>
              <p class="text-center">Поставщикам</p>
            </div>
          </li>
          <li class="nav-item flex-fill">
            <div class="navigation-block__item-last position-relative">
              <div class="dropdown dropup text-center">
                <a class="dropdown-toggle p-0" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                  Личный кабинет
                </a>
                <div class="dropdown-menu border-danger position-absolute" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item text-center" href="{% url 'app_shop:authentication' %}">Войти</a>
                  <a class="dropdown-item text-center" href="{% url 'app_shop:authentication' %}">Зарегистрироваться</a>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </nav>
    </div>
    <!-- navigation end -->
    <!-- sub-navigation -->
    <div class="sub-navigation-block container">
      <nav class="navbar navbar-light bg-light p-0">
        {% block sub-navigation %}
        {% endblock %}
      </nav>
      <div class="sub-navigation-block__name-page">
        <p class="sub-navigation-block__name-text">
          {% block name-page %}
          {{ object.title }}
          {% endblock %}
        </p>
      </div>
    </div>
    <!-- sub-navigation end -->
    <!-- content -->
    <div class="content-block">
      {% block content %}
      {% endblock %}
    </div>
    <!-- content end -->
    <!-- footer -->
    <footer class="footer-block container p-0">
      <nav class="footer-block__nav navbar py-0">
        <ul class="navbar-nav flex-row align-items-center text-center w-50">
          <li class="nav-item flex-fill">
            <a class="nav-link p-0" href="{% url 'app_shop:subpage_allhere_in_russia' 'feedback' %}">
              Обратная связь
            </a>
          </li>
          <li class="nav-item flex-fill">
            <a class="nav-link p-0" href="{% url 'app_shop:news' %}">
              Новости
            </a>
          </li>
          <li class="nav-item flex-fill">
            <a class="nav-link p-0" href="#">
              Политика конфиденциальности
            </a>
          </li>
        </ul>
      </nav>
    </footer>
    <!-- footer end -->
  </div>
</body>
</html>

app_shop/templates/subpage_allhere_in_russia/allhere_news.html
{% extends "subpage_allhere_in_russia/allhere_in_russia.html" %}


{% block title %}
<title>AllHere в России | Новости | {{ object.title }}</title>
{% endblock %}

{% block name-page %}
Новости
{% endblock %}

{% block content %}
<div class="news-block row">
  {% if object %}
  <div class="news-block__news-list col-4">
    <div class="list-group">
      {% for news in news_list %}
      <a href="{% url 'app_shop:news' news.id %}"
         class="list-group-item list-group-item-action {% if news.title == object.title %}active{% endif %}">
        {{ news.title }} <small>({{ news.datetime }})</small>
      </a>
      {% endfor %}
    </div>
  </div>
  <div class="news-block__news-text col-8">
    <h6 class="mb-2">Опубликовано {{ news.datetime }}</h6>
    <hr>
    <h3 class="text-center mb-2">{{ news.title }}</h3>
    <hr>
    {{ object.body|safe }}
  </div>
  {% else %}
  <h3 class="text-center mx-auto my-5">Новостей пока нет</h3>
  {% endif %}
  <div class="news-block__footer col-12">
    <h3>Контакты для прессы:</h3>
    <p><a href="mailto:pressa@allhere.ru">e-mail: pressa@allhere.ru</a></p>
    <p>Телефон: <a href="tel:+74957212090">(495) 721-20-90</a>, доб. *1020, *1033, *1568</p>
    <p>Руководитель пресс-службы Джозефина Уткина</p>
  </div>
</div>
{% endblock %}

app_shop/templates/subpage_allhere_in_russia/allhere_shops.html
{% extends "subpage_allhere_in_russia/allhere_in_russia.html" %}


{% block title %}
<title>Наши магазины</title>
{% endblock %}

{% block sub-navigation %}
<ul class="navbar-nav flex-row align-items-center w-100">
  <li class="nav-item flex-fill">
    <p class="text-center">Выберите ближайший к вам магазин</p>
  </li>
  <li class="nav-item flex-fill">
    <div class="dropdown text-center">
      <a class="dropdown-toggle p-0" type="button" id="dropdownMenuShopsAllHere" data-toggle="dropdown"
         aria-haspopup="true" aria-expanded="false">
        AllHere
      </a>
      <div class="dropdown-menu position-absolute" aria-labelledby="dropdownMenuShopsAllHere">
        {% for item in shops_list %}
        {% if item.type.title == 'AllHere' %}
        <a class="dropdown-item" href="{% url 'app_shop:shop_detail' item.id %}">{{ item.city }} / {{ item.name }}</a>
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </li>
  <li class="nav-item flex-fill">
    <div class="dropdown text-center">
      <a class="dropdown-toggle p-0" type="button" id="dropdownMenuShopsAllHereGarden" data-toggle="dropdown"
         aria-haspopup="true" aria-expanded="false">
        AllHere Сад
      </a>
      <div class="dropdown-menu position-absolute" aria-labelledby="dropdownMenuShopsAllHereGarden">
        {% for item in shops_list %}
        {% if item.type.title == 'AllHere Сад' %}
        <a class="dropdown-item" href="{% url 'app_shop:shop_detail' item.id %}">{{ item.city }} / {{ item.name }}</a>
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </li>
  <li class="nav-item flex-fill">
    <div class="dropdown text-center">
      <a class="dropdown-toggle p-0" type="button" id="dropdownMenuShopsAllHereCity" data-toggle="dropdown"
         aria-haspopup="true" aria-expanded="false">
        AllHere Сити
      </a>
      <div class="dropdown-menu position-absolute" aria-labelledby="dropdownMenuShopsAllHereCity">
        {% for item in shops_list %}
        {% if item.type.title == 'AllHere Сити' %}
        <a class="dropdown-item" href="{% url 'app_shop:shop_detail' item.id %}">{{ item.city }} / {{ item.name }}</a>
        {% endif %}
        {% endfor %}
      </div>
    </div>
  </li>
</ul>
{% endblock %}

{% block content %}
{% block map %}
{% endblock %}
<div class="content-block__city-list col-11 col-md-4">
  <h4 class="text-center">Наши магазины можно найти в городах:</h4>
  <div class="row justify-content-center">
    <div class="col-8 my-2">
      {% for city in city_list %}
      <p>{{ city }}</p>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}